package CO1JavaFundamentals;


/*
============================================================
        CO1.2 - JDK, JRE AND JVM
============================================================

Topic:
JDK (Java Development Kit)
JRE (Java Runtime Environment)
JVM (Java Virtual Machine)

------------------------------------------------------------
1. WHAT IS JDK?
------------------------------------------------------------

JDK stands for Java Development Kit.

JDK is a complete software development kit used to
develop, compile, debug and run Java programs.

In simple words:

JDK = Tools required to DEVELOP Java applications.

JDK contains:
    - JRE
    - JVM
    - Java Compiler (javac)
    - Debugging tools
    - Documentation tools
    - Other development utilities

Example:

If we write a Java program:

    CO1_2_JDK_JRE_JVM.java

The JDK provides the compiler:

    javac

which converts the Java source code into bytecode.

------------------------------------------------------------
2. WHAT IS JRE?
------------------------------------------------------------

JRE stands for Java Runtime Environment.

JRE provides the environment required to RUN Java
applications.

In simple words:

JRE = Environment required to RUN Java programs.

JRE mainly consists of:

    - JVM
    - Java Class Libraries
    - Supporting files

JRE does NOT provide the Java compiler (javac).

Therefore, JRE is mainly used for running Java programs,
while JDK is used for developing Java programs.

------------------------------------------------------------
3. WHAT IS JVM?
------------------------------------------------------------

JVM stands for Java Virtual Machine.

JVM is responsible for executing Java bytecode.

In simple words:

JVM = The engine that EXECUTES Java bytecode.

Java source code is first compiled into bytecode.

Example:

    CO1_2_JDK_JRE_JVM.java
                |
                | javac
                ↓
    CO1_2_JDK_JRE_JVM.class
                |
                | JVM
                ↓
           Program Output

JVM makes Java platform independent because the same
bytecode can run on different operating systems if a
compatible JVM is available.

------------------------------------------------------------
4. WHY IS JVM CALLED A VIRTUAL MACHINE?
------------------------------------------------------------

JVM is called a Virtual Machine because it behaves like
a machine inside the computer that provides an execution
environment for Java bytecode.

It does not directly depend on the physical CPU in the
same way as native machine code.

Different operating systems can have different JVM
implementations.

For example:

    Windows → JVM
    Linux   → JVM
    macOS   → JVM

The same Java bytecode can run on all of them.

------------------------------------------------------------
5. JAVA SOURCE CODE
------------------------------------------------------------

Java source code is the code written by the programmer.

File extension:

    .java

Example:

    CO1_2_JDK_JRE_JVM.java

Example code:

    public class CO1_2_JDK_JRE_JVM {
        public static void main(String[] args) {
            System.out.println("Hello Java");
        }
    }

------------------------------------------------------------
6. JAVA COMPILER - JAVAC
------------------------------------------------------------

javac is the Java compiler provided by the JDK.

It converts:

    Java Source Code (.java)
            ↓
          javac
            ↓
    Java Bytecode (.class)

Example:

    javac CO1_2_JDK_JRE_JVM.java

After compilation:

    CO1_2_JDK_JRE_JVM.class

is generated.

------------------------------------------------------------
7. JAVA BYTECODE
------------------------------------------------------------

Bytecode is the intermediate code generated by the Java
compiler.

File extension:

    .class

Bytecode is not directly written by the programmer.

It is generated by javac.

Example:

    CO1_2_JDK_JRE_JVM.java
            ↓
          javac
            ↓
    CO1_2_JDK_JRE_JVM.class

The JVM executes this bytecode.

------------------------------------------------------------
8. COMPLETE JAVA EXECUTION FLOW
------------------------------------------------------------

The complete basic flow is:

    Java Source Code
          |
          |  javac
          ↓
    Java Bytecode
          |
          |  JVM
          ↓
    Machine-level execution
          |
          ↓
        Output


Example:

    CO1_2_JDK_JRE_JVM.java
              |
              ↓
           javac
              |
              ↓
    CO1_2_JDK_JRE_JVM.class
              |
              ↓
             JVM
              |
              ↓
       Program Execution
              |
              ↓
        Hello Java


------------------------------------------------------------
9. JDK vs JRE vs JVM
------------------------------------------------------------

JDK:
    - Full development kit
    - Used to develop Java programs
    - Contains compiler and development tools
    - Used by Java developers

JRE:
    - Runtime environment
    - Used to run Java applications
    - Provides libraries and JVM

JVM:
    - Executes Java bytecode
    - Provides the runtime execution engine
    - Helps Java achieve platform independence

------------------------------------------------------------
10. SIMPLE RELATIONSHIP
------------------------------------------------------------

Conceptually:

        JDK
         |
         ↓
        JRE
         |
         ↓
        JVM


Remember:

    JDK → DEVELOP
    JRE → RUN
    JVM → EXECUTE

------------------------------------------------------------
11. REAL-LIFE EXAMPLE
------------------------------------------------------------

Think of Java development like making a movie.

JDK:
    Complete movie-making studio.
    It provides all the tools needed to create the movie.

JRE:
    Environment required to play the movie.

JVM:
    The player/engine that actually executes the
    Java bytecode.

Java Program:
    The movie/content being created.

------------------------------------------------------------
12. PLATFORM INDEPENDENCE
------------------------------------------------------------

Java follows the principle:

    "Write Once, Run Anywhere"

This means that a Java program can be compiled into
bytecode once and the bytecode can run on different
operating systems using their compatible JVM.

Example:

    Same Java Bytecode
           |
      -----------------
      |       |       |
      ↓       ↓       ↓
   Windows   Linux   macOS
     JVM      JVM      JVM

This is one of the major advantages of Java.

------------------------------------------------------------
13. IMPORTANT TERMS
------------------------------------------------------------

JDK:
    Java Development Kit

JRE:
    Java Runtime Environment

JVM:
    Java Virtual Machine

javac:
    Java Compiler

.java:
    Java Source Code file

.class:
    Java Bytecode file

Bytecode:
    Intermediate code generated by the Java compiler

------------------------------------------------------------
14. IMPORTANT COMMANDS
------------------------------------------------------------

To compile a Java program:

    javac CO1_2_JDK_JRE_JVM.java

To run a compiled Java class:

    java CO1_2_JDK_JRE_JVM

Note:

    javac → Compiles the program
    java  → Runs the program using the JVM

------------------------------------------------------------
17. PRACTICAL EXAMPLE
------------------------------------------------------------

Source file:

    CO1_2_JDK_JRE_JVM.java

Compile:

    javac CO1_2_JDK_JRE_JVM.java

Generated file:

    CO1_2_JDK_JRE_JVM.class

Run:

    java CO1_2_JDK_JRE_JVM

Output:

    Hello Java

------------------------------------------------------------
18. KEY POINT TO REMEMBER
------------------------------------------------------------

            JDK
             |
             ↓
    Development + Tools
             |
             ↓
            JRE
             |
             ↓
       Runtime Environment
             |
             ↓
            JVM
             |
             ↓
      Executes Bytecode


FINAL REMEMBER:

    JDK → DEVELOP
    JRE → RUN
    JVM → EXECUTE

============================================================
                    END OF CO1.2
============================================================
*/

public class C02_JDK_JRE_JVM {

    public static void main(String[] args) {

        System.out.println("Hello Java");

    }
}
